config/routes.rb
ReserveMe::Application.routes.draw do

  get "owners/dashboard"
  resources :reservations
  

  devise_for :owners

    authenticated :owner do
      root to:'owners#dashboard', as:'authenticated_root'
    end
  root to: 'restaurants#index'

  resources :restaurants do
    resources :reservations
  end
  resources :owners

  

end

app/models/owner.rb
class Owner < ActiveRecord::Base
# attr_accessor :first_name, :last_name
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :restaurants

  validates :name, :email, :presence => true
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  validates :email, :requested_date_time, presence:true

  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  validates :name, :description, :address, :phone_number, presence:true
  validates :name, :address, length: { minimum: 4 }
  validates :phone_number, length: { minimum: 10 }
  validates :owner, :presence => true
  
  mount_uploader :avatar, AvatarUploader

  belongs_to :owner
  has_many :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end  
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController

	def dashboard
    @restaurants = Restaurant.where(owner: current_owner)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reservation = @restaurant.reservations.new
  end

  def show
  	@reservation = Reservation.find(params[:id])
  end

  def create
  	@restaurant = Restaurant.find(params[:restaurant_id])
  	@reservation = @restaurant.reservations.new(reservation_params)

  	if @reservation.save
      ReservationMailer.reservation_confirmation(@user).deliver
  		redirect_to restaurant_reservation_path(@reservation.restaurant_id,
  		 @reservation.id)
  	else
  		render 'new'
  	end
  end

  def index
  	@restaurant = Restaurant.find(params[:restaurant_id])
  	if owner_signed_in? && current_owner == @restaurant.owner
  		@reservations = @restaurant.reservations
  	else
  		flash[:notice] = "You are not Authorized for this action!"
  		redirect_to restaurants_path
  	end
  end

  def edit
  	@reservation = Reservation.find(params[:id])
  end

  def destroy
  	@restaurant = Restaurant.find(params[:restaurant_id])
  	@reservation = @restaurant.reservations.find(params[:id])

  	if current_owner == @reservation.restaurant.owner
  		@reservation.destroy
  		redirect_to restaurant_reservations_path(@reservation.restaurant_id)
  	else
  		flash[:notice] = "You are not authorized to delete this reservation!"
  		redirect_to restaurants_path
  	end
  end

  private
  def reservation_params
  	params.require(:reservation).permit(:email, :requested_date_time, :message)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_filter :authenticate_owner!

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @address = @restaurant.address
    @gmaps_key = ENV['G_MAP_API_KEY']
    @owner = current_owner
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    # I notice that you are premitting some of the fields on create, but not the avatar/avatar_url
    # Is that intended?
    #
    # @restaurant = Restaurant.new(params[:restaurant].permit(:name, :description,
    #   :address, :phone_number))
    # @restaurant.owner = current_owner

    # this line is a little sloppy still, so i might pull it into a separate get restaurant params method
    # especially if it is reused below.  I see your post_params method which is exactly the right idea.  Just didn't
    # get used above.
    merged_params = params.require(:restaurant)
                      .permit(:name, :description, :address, :phone_number)
                      .merge({ owner_id: current_owner.id })

    if @restaurant = Restaurant.create(merged_params)
      redirect_to @restaurant
    else
      render 'new'
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])

    # Doesn't look like you're
    # checking if the restaurant's current owner is the current owner...

    #I'll add a check here in line... you could create a private method and use it as a filter instead...
    if @restaurant.owner != current_owner
      flash[:error] = "Restaurant NOT updated - You must be the restaurant owner to make edits!"
      return redirect_to @restaurant
    end

    # Here's the other place to reuse that params method.
    if @restaurant.update(params[:restaurant].permit(:name, :description,
     :address, :phone_number, :avatar, :avatar_url))
      redirect_to @restaurant
    else
      render 'edit'
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    redirect_to restaurants_path
  end


  private
    def post_params
      params.require(:restaurant).permit(:name, :description, :address,
       :phone_number, :avatar, :avatar_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReserveMe</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<div class="navbar navbar-collapse"><body id='body1'>
  <div ><% if owner_signed_in? %>
    <h4 class='successful-login'>You have successfully logged in <%= current_owner.name %>!</h4>
    <%= link_to "Sign Out", destroy_owner_session_path, :method => :delete %>
    | <%= link_to "Edit Profile",edit_owner_registration_path %>
    | <%= link_to "My Dashboard", owners_dashboard_path %></div>

  <% else %>

    <h1> Welcome to Reserve.Me!</h1>
    <%= link_to "Sign In", new_owner_session_path, method: :get %>
    | <%= link_to "Sign Up", new_owner_registration_path, method: :get %>
  <% end %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
 

<%= yield %>

</body>
</html>

app/views/owners/dashboard.html.erb
<h2>Welcome to your dashboard</h2>

<div class='container bs-docs-container'>
<h1>Your Restaurants</h1>
<h3>Current Owner ID: <%= current_owner.id %></h3>
<table class='table table-striped table-hover table-responsive'>
  <tr>
    <th>Image</th>
    <th>Name</th>
    <th>Description</th>
    <th>Address</th>
    <th>Phone Number</th>
    <th></th>
    <th></th>
  </tr>

  
    <% @restaurants.each do |restaurant| %>
    <tr>
      <td><%= image_tag restaurant.avatar_url(:thumb), :class => "img-rounded" %></td>
      <td><%= restaurant.name %></td>
      <td><%= restaurant.description %></td>
      <td><%= restaurant.address %></td>
      <td><%= restaurant.phone_number %></td>
      <td><%= link_to "Show Restaurant", restaurant_path(restaurant), :class =>'btn btn-primary' %></td>
        <td><%= link_to "Edit Restaurant", edit_restaurant_path(restaurant), :class =>'btn btn-default' %></td>
      <td><%= link_to 'Delete', restaurant, :class =>'btn btn-danger', method: :delete, data:
       { confirm:"Are you sure?" }  %></td>
    <% end %>
  </tr>

  <%= link_to "New Restaurant", new_restaurant_path, :class =>'btn btn-success' %>

</table>
</div>

<h2><%= link_to "See All Restaurants", restaurants_path %></h2>

app/views/owners/edit.html.erb
<h3>Edit Account</h3>
<%= redirect_to edit_owner_path(@owner) %>

app/views/reservations/_form.html.erb
<form class="form-horizontal"><%= form_for @reservation, url: restaurant_reservations_path do |f| %>
 
<div class="reservation-form">               
	<p>        
	  <%= f.label :email %>
	  <%= f.text_field :email %>
	</p>

	<p>
	  <%= f.label :requested_date_and_time %>
	   <p><%= f.date_select :requested_date_time, {:order => [:month, :day, :year],
	   	:prompt => true, :start_year => Time.now.year, :end_year => Time.now.year + 1} %></p>
	   	<p class="time-field"><%= time_field(:requested_date_time, :started_at => Time.now) %></p>
	</p>

	<p>
	  <%= f.label :message %>
	  <%= f.text_area :message %>
	</p>

	<p>
	  <%= f.submit "Save reservation" %>
	</p>
	</form>
</div>
<% end %>

app/views/reservations/index.html.erb
<h2>All Reservations</h2>

<% if @reservations.nil? %>
<h4>No reservations currently listed</h4>
<%= link_to "Back", restaurants_path %>

<% else %>

<table class="table talbe-striped table-bordered">
	<tr>
		<th>Email: </th>
		<th>Date & Time: </th>
		<th>Message: </th>
	</tr>	

	<% @reservations.each do |reservation| %>
	<tr>
		<td><%= reservation.email %></td>
		<td><%= reservation.requested_date_time %></td>
		<td><%= reservation.message %></td>
		<td><%= link_to "Delete Reservation",restaurant_reservation_path(reservation.restaurant_id,
		 reservation.id), method: :delete, data: {confirm: "Are you sure?"} %></td>
	</tr>
	<% end %>
</table><br>

<%= link_to "Back to restaurant", restaurant_path(@restaurant) %>

<% end %>

app/views/reservations/new.html.erb
<h2>Make a reservation:</h2>

<%= render 'form' %>

<%= link_to "Back to restaurant", restaurant_path(@restaurant) %>

app/views/reservations/show.html.erb
<h3>Reservation Confirmed: </h3>

<strong>Email Address:</strong><%= @reservation.email %><br>
<strong>Date &amp; Time:</strong><%= @reservation.requested_date_time %><br>
<strong>Message: </strong><%= @reservation.message %><br>

<%= link_to "Back", restaurant_path(@reservation.restaurant) %>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant, :html => {:multipart => true} do |f| %>
  <% if @restaurant.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited
      this restaurant from being saved:</h2>
    <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </p>

  <p>
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </p>

  <p>
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path, class:'btn btn-primary' %>

app/views/restaurants/index.html.erb
<div class='bck'>
  <div class='container bs-docs-container'>
  <h1 class='restaurant-list-header'>Restaurant List</h1>
  <!-- <h3>Current Owner ID: <%= current_owner.id %></h3> -->
  <table class='table table-hover table-responsive table-bordered' id="main-table">
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Description</th>
      <th>Address</th>
      <th>Phone Number</th>
      <th>Owner ID</th>
      <th></th>
      <th></th>
    </tr>

    
      <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= image_tag restaurant.avatar_url(:thumb), :class => "img-rounded" %></td>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.description %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.phone_number %></td>
        <td><%= restaurant.owner_id %></td>
        <td><%= link_to "Show Restaurant", restaurant_path(restaurant), :class =>'btn btn-primary' %></td>
        <% if current_owner.id == restaurant.owner_id %>
          <td><%= link_to "Edit Restaurant", edit_restaurant_path(restaurant), :class =>'btn btn-default' %></td>
        <td><%= link_to 'Delete', restaurant, :class =>'btn btn-danger', method: :delete, data:
         { confirm:"Are you sure?" }  %></td>
        <% end %>
      <% end %>
    </tr>

    <%= link_to "New Restaurant", new_restaurant_path, :class =>'btn btn-success' %>

  </table>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class='container bs-docs-container'>
<h1>New Restaurant</h1>

<%= render 'form' %>
 
<%= link_to 'Back', restaurants_path, :class=>'btn btn-primary' %>
</div>

app/views/restaurants/show.html.erb
<div class='container bs-docs-container'>
  <% if @restaurant.owner == nil %>
    <h4> Restaurant does not currently have an owner on file </h4>
  <% else %>
    <h3> Owned by: <%= @restaurant.owner.name %></h3>
  <% end %>

<table>
  <tr>
      <%= image_tag @restaurant.avatar_url(:thumb) %>
  </tr>
  <tr>
    <td>
      <strong>Name:</strong> <%= @restaurant.name %>
    </td>
  </tr>
  <tr>
    <td>
      <strong>Description:</strong> <%= @restaurant.description %>
    </td>
  </tr>
  <tr>
    <td>
      <strong>Address:</strong> <%= @restaurant.address %>
    </td>
  </tr>
  <tr>
    <td>
      <strong>Phone Number:</strong> <%= @restaurant.phone_number %>
    </td>
  </tr>
</table>
<br>
<%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{url_encode(@restaurant.address)}&markers=color:red|#{url_encode(@restaurant.address)}&zoom=14&size=200x200&sensor=false&key=AIzaSyCzFcVAF6FmVvdJomC1mzaeMLNBCoNJcGI"  %>
<br>
<br>


<% if @restaurant.owner == current_owner %>
<h3><%= link_to "Show All Reservations", restaurant_reservations_path(@restaurant)%></h3>
  <%= link_to "Edit", edit_restaurant_path %>
  | <%= link_to "Destroy", restaurant_path(@restaurants), :method => :delete, data:
    {confirm: 'Are you sure?'} %>
<% else %>
<h3><%= link_to "Make a reservation", new_restaurant_reservation_path(@restaurant) %></h3>
<% end %>
| <%= link_to "Back to List", restaurants_path %>
</div>